---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

platforms:
  - name: instance
    image: ubuntu:22.04
    command: sleep infinity
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  env:
    ANSIBLE_REMOTE_TMP: /tmp/.ansible/tmp
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
      interpreter_python: auto_silent
  inventory:
    host_vars:
      instance:
        ansible_connection: community.docker.docker
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: converge.yml
    destroy: destroy.yml

verifier:
  name: ansible

scenario:
  test_sequence:
    - create
    - prepare
    - converge
    - verify
    - destroy
