---
- name: verifier l etat du système
  hosts: all
  become: true
  gather_facts: true
  tasks:
    # 1. Vérification du Paquet: Utilisation de package_facts
    - name: Récupérer les faits sur les paquets
      ansible.builtin.package_facts:
        manager: auto
    
    - name: Assertion Paquet curl
      ansible.builtin.assert:
        that:
          - "'curl' in ansible_facts.packages"
        fail_msg: "Le paquet 'curl' n'est pas installé."
        success_msg: "✓ Le paquet curl est installé"
    
    # 2. Vérification du Fichier
    - name: verifier que le fichier /tmp/fichier_cree existe
      ansible.builtin.stat:
        path: /tmp/fichier_cree
      register: file_check
    
    - name: Assertion Fichier
      ansible.builtin.assert:
        that:
          - file_check.stat.exists
        fail_msg: "Le fichier /tmp/fichier_cree n'existe pas."
        success_msg: "✓ Le fichier /tmp/fichier_cree existe"
    
    # 3. Vérification du Service
    - name: Vérifier l'état des services
      ansible.builtin.service_facts:
    
    - name: Debug services disponibles
      ansible.builtin.debug:
        msg: "{{ ansible_facts.services.keys() | select('search', 'cron') | list }}"
    
    - name: Assertion Service cron
      ansible.builtin.assert:
        that:
          - "'cron' in ansible_facts.services"
          - "ansible_facts.services['cron'].state == 'running'"
        fail_msg: "Le service 'cron' n'est pas actif ou introuvable."
        success_msg: "✓ Le service cron est actif"
